// Generated by https://quicktype.io

export interface IAgendaResponse {
  agendaId: number;
  startTime: string;
  endTime: string;
  room: string;
  sessionId: number;
  session: Session;
  rowSpan?: number;
}

export interface Session {
  title: string;
  description: string;
  sessionType: SessionType | null;
  level: Level | null;
  duration: number;
  firstName: string;
  lastName: string;
  photoUrl: string;
  agendas: null;
}

export enum Level {
  Avanzado = "Avanzado",
  Intermedio = "Intermedio",
  Principiante = "Principiante",
}

export enum SessionType {
  SesionAlterna = "Sesion alterna",
  SesionRegular = "Sesion regular",
  Workshop = "Workshop",
}
