// Generated by https://quicktype.io

export interface ISpeakerResponse {
  speakerId: number;
  firstName: string;
  lastName: string;
  title: string;
  email: string;
  bio: string;
  photoUrl: null | string;
  twitterHandle: null | string;
  linkedInProfile: null | string;
  gitHubProfile: null | string;
  website: null | string;
}
